import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/landingpage">Landingpage</Link>
        </li>
        <li>
          <Link to="/factories">Factories</Link>
        </li>
        <li>
          <Link to="/factoriesdetails">FactoriesDetails</Link>
        </li>
        <li>
          <Link to="/factoriesdetailsone">FactoriesDetailsOne</Link>
        </li>
        <li>
          <Link to="/frameone">FrameOne</Link>
        </li>
        <li>
          <Link to="/one">One</Link>
        </li>
        <li>
          <Link to="/two">Two</Link>
        </li>
        <li>
          <Link to="/three">Three</Link>
        </li>
        <li>
          <Link to="/nine">Nine</Link>
        </li>
        <li>
          <Link to="/four">Four</Link>
        </li>
        <li>
          <Link to="/five">Five</Link>
        </li>
        <li>
          <Link to="/seven">Seven</Link>
        </li>
        <li>
          <Link to="/eight">Eight</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
